//default language map

var m;
m=global.strmap

global.sysfont=spr_sysfont

game_addlang(m,"name","English")
game_lflang()
game_addlang(m,"charmap","#################################¡########ª«#########µ####º»###¿ÀÁÂÃÄÅÆÇÈÉÊËÌÍÎÏ#ÑÒÓÔÕÖ##ÙÚÛÜ##ßàáâãäåæçèéêëìíîï#ñòóôõö##ùúûüý#ÿ")
game_lflang()
game_addlang(m,"menu start","Press Any Button")
game_lflang()
game_addlang(m,"first","Hey there! Looks like this is the first time you launch the game. Hit F1 to learn more about each screen.##If you need instructions on how to get through the game, check out the enclosed instruction book.")
game_addlang(m,"first skin","Looks like you've just changed your character's skin for the first time.#Skins change how the character looks, but they don't change the gameplay!")
game_lflang()
game_addlang(m,"opts key","       KEYBOARD")
game_addlang(m,"opts joy","       GAMEPAD")
game_addlang(m,"key name","KEYBOARD: ")
game_addlang(m,"key set","SET KEYS")
game_addlang(m,"joy set","SET BUTTONS")
game_addlang(m,"key end","SAVE AND RETURN")
game_addlang(m,"key cancel","CANCEL")
game_lflang()
game_addlang(m,"up","UP")
game_addlang(m,"down","DOWN")
game_addlang(m,"left","LEFT")
game_addlang(m,"right","RIGHT")
game_addlang(m,"jump","JUMP")
game_addlang(m,"action","ACTION")
game_addlang(m,"alt","ALT")
game_addlang(m,"start","START")
game_lflang()
game_addlang(m,"pause","P A U S E")
game_addlang(m,"pause quit ask","Quit Game?")
game_addlang(m,"pause resume","Resume")
game_addlang(m,"pause back","Back")
game_addlang(m,"pause skip","Skip stage")
game_addlang(m,"pause retry","Retry stage")
game_addlang(m,"pause window","Window")
game_addlang(m,"pause volume","Balance")
game_addlang(m,"pause quit","Quit")
game_lflang()
game_addlang(m,"mm 0","Start Game")
game_addlang(m,"mm 1","Go Back")
game_addlang(m,"mm 2","Quick Play")
game_addlang(m,"mm 3","Configuration")
game_addlang(m,"mm 4","Watch Replays")
game_addlang(m,"mm 5","Exit Game")
game_addlang(m,"mm 6","Level Editor")
game_addlang(m,"mm 7","Staff Roll")
game_addlang(m,"mm 8","Bundles")
game_addlang(m,"mm 9","Match Options")
game_addlang(m,"mm 10","-S- fucks around to create a character creator")
game_addlang(m,"mm 11","Discord")
game_addlang(m,"mm 12","GameBanana")
game_addlang(m,"mm 13","Character Bios")
game_addlang(m,"mm 14","Mod Loader")
game_addlang(m,"mm legends","Press %jump% to jump.")
game_lflang()
game_addlang(m,"cog menu","Match Options")
game_addlang(m,"cog mirror","Mirror Mode")
game_addlang(m,"cog ratchet","Screen Ratchet")
game_addlang(m,"cog random blocks","Random Items")
game_lflang()
game_addlang(m,"roster ready","Press Start!")
game_addlang(m,"roster cast","Main Cast: ")
game_addlang(m,"roster charmcast","Charms: ")
game_addlang(m,"stage ready","GO!")
game_addlang(m,"tasready","Press START when ready")
game_lflang()
game_addlang(m,"replays","Replays")
game_lflang()
game_addlang(m,"mods","Mod Loader")
game_addlang(m,"mod folder","Open folder")
game_addlang(m,"mod enable","Enabled")
game_addlang(m,"mod broken","This charm file contains errors and is disabled, check errors.txt for more information.")
game_addlang(m,"mod ok","Loaded")
game_addlang(m,"mod no","Disabled")
game_addlang(m,"mod bk","Broken")
game_lflang()
game_addlang(m,"default music","Load from#world skin")
game_addlang(m,"default levels","Base game#levels")
game_lflang()
game_addlang(m,"stage screen","Choose World")
game_addlang(m,"stage screen2","Next Stage")
game_addlang(m,"stage mode 0","Sequence")
game_addlang(m,"stage mode 1","Choose")
game_addlang(m,"stage mode 2","Shuffle")
game_lflang()
game_addlang(m,"bundle screen","Select Bundle")
game_lflang()
game_addlang(m,"score title","RESULTS")
game_addlang(m,"score final title","FINAL RESULTS")
game_addlang(m,"score wins","WINS!")
game_addlang(m,"score ties","TIED - TRY AGAIN!")
game_addlang(m,"score 0","Score")
game_addlang(m,"score 1","Enemies")
game_addlang(m,"score 2","Blocks")
game_addlang(m,"score 3","Coins")
game_addlang(m,"score 4","TotCoin")
game_addlang(m,"score 5","Time")
game_addlang(m,"score 6","Items")
game_addlang(m,"score 7","Frags")
game_addlang(m,"score 8","Deaths")
game_addlang(m,"score 9","Perfect")
game_lflang()
game_addlang(m,"unlock kid","You unlocked##The Kid!")
game_addlang(m,"unlock super","You unlocked##Super Sonic!")
game_addlang(m,"unlock ashura","You unlocked##Ashura!")
game_lflang()
game_addlang(m,"tip world","Press %jump% to jump. %action% is the run and fire button.")
game_addlang(m,"tip main menu","Click one of the icons to select a mode. You can use the mouse or any of the gamepads.")
game_addlang(m,"tip options","Change the game options here. Check the manual for keyboard shortcuts.")
game_addlang(m,"tip replays","Recorded matches show up here where you can watch them play back.##Hit F12 to hide the replay UI.")
game_addlang(m,"tip roster","Click a character card to pick it. Click or hold on the player box to change skins.")
game_addlang(m,"tip stage select","You can right click or press b on a world skin to use that skin as a music pack.")
game_addlang(m,"tip optfilter","Choose video filter mode.##Performance is unaffected.")
game_addlang(m,"tip optvideo","Choose your preferred window size.##You can press F11 or F4 to change this at any time.")
game_addlang(m,"tip optextract","Extracts the game's base assets so you can use them as examples to make mods and skins.")
game_addlang(m,"tip optstats","View your personal game statistics.")
game_addlang(m,"tip optkey","Change button mappings for keyboards 1 and 2.")
game_addlang(m,"tip optjoy","Change gamepad button mappings for all connected gamepads.")
game_addlang(m,"tip optegg","Disables all random jokes and easter eggs.##Useful for streaming!")
game_addlang(m,"tip optdiscord","Choose wether or not to display your activity to your Discord profile.##You may notice some delay when toggling the setting.")
game_addlang(m,"tip optvol","Balance between the music and sound effects.##For muting the game, please use the system volume mixer.")
game_addlang(m,"tip optassets","Removes decorations and some background elements to increase performance.")
game_addlang(m,"tip optlang","Choose user interface language.##This does not affect text on levels.")
game_addlang(m,"tip optdetail","Reduces background update speed to 30 fps for better performance.")
game_addlang(m,"tip optmusic","You can choose an ogg file to use as custom menu music.")
game_addlang(m,"tip optmusic2","Custom menu music:#")
game_addlang(m,"tip optpause","Choose if the game can automatically pause when it's not the foreground window.")
game_addlang(m,"tip optcamshim","Changes how much the camera extends while doing certain actions.")
game_lflang()
game_addlang(m,"tip unlock ashura","What happens in the minus world?")
game_addlang(m,"tip unlock super","The 7 Chaos Emeralds hold a mysterious power...")
game_addlang(m,"tip unlock kid","Have you ever gone the wrong way?")
game_addlang(m,"tip unlock dio","How many breads have you eaten in your life?")
game_lflang()
game_addlang(m,"error bundles","No bundles were found.##Place your bundles here:##")
game_addlang(m,"error identical gamepads","You have identical controllers. Changing the settings for one of them will affect the other ones.")
game_addlang(m,"error press","Press F9 to screenshot, Escape to#exit or any other key to continue:")
game_addlang(m,"error skin type","Invalid skin type: ")
game_addlang(m,"error skin string","Missing skin string: ")
game_addlang(m,"error movie corrupt","Movie data is corrupt.")
game_addlang(m,"error movie charm","Error loading movie:##Movie contains charm character '")
game_addlang(m,"error movie charm 2","', which is not installed.")
game_addlang(m,"error no joy config","There are no connected gamepads.")
game_addlang(m,"error skin dimensions","Incorrect image dimensions loading skin.")
game_addlang(m,"error skin thicc","Skin texture too large, loading failed.")
game_addlang(m,"error world icon size","Skin icons must be 96x48: ")
game_addlang(m,"error bundle icon size","Bundle icons must be 96x96: ")
game_addlang(m,"error skin corrupt","Found corrupt image loading skin.")
game_addlang(m,"error next version","This content is not yet available. Check next version.")
game_addlang(m,"error too many","Only 4 players can join.")
game_addlang(m,"error crash","Looks like the game had errors last time. Please send the crash logs to us on Discord so we can fix them.")
game_addlang(m,"error steam desktop controller","Seems like you have Steam or joy2key interfering with your keyboard. Please disable those programs since they're not necessary here.")
game_addlang(m,"error bundle missing","This bundle is missing either a level pack or a world skin and can't be used.")
game_addlang(m,"error lemon version","The loaded lemon file is corrupt and can't be used.")
game_addlang(m,"error lemon converted","The loaded lemon file is an old format and has been converted. Some objects may be missing.")
game_lflang()
